
parameters:
- name: runPerfTests
  type: boolean
  default: false
- name: image
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
- name: myNumber
  type: number
  default: 2
  values:
  - 1
  - 2
  - 4
  - 8
  - 16
- name: configs
  type: string
  default: 'x86,x64'
  
  
trigger: none

pool: 30530-ICAP-SDP-DevOps-AgentPool

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - script: echo running Build
  - ${{ if contains(parameters.configs, 'x86') }}:
    - job: x86
      steps:
       - script: echo Building x86...
  - ${{ if contains(parameters.configs, 'x64') }}:
    - job: x64
      steps:
      - script: echo Building x64...
  - ${{ if contains(parameters.configs, 'arm') }}:
    - job: arm
      steps:
      - script: echo Building arm...
    

- stage: UnitTest
  displayName: Unit Test
  dependsOn: Build
  jobs:
  - job: UnitTest
    steps:
    - script: echo running UnitTest 
      displayName: this is Unit Test
    - script: echo  ${{parameters.image}} 
      displayName: this is image
    - script: echo building $(Build.BuildNumber) with ${{ parameters.myNumber }} 
      displayName: this is my number

- ${{ if eq(parameters.runPerfTests, true) }}:
  - stage: PerfTest
    displayName: Performance Test
    dependsOn: Build
    jobs:
    - job: PerfTest
      steps:
      - script: echo running PerfTest


- stage: Deploy
  displayName: Deploy
  dependsOn: UnitTest
  jobs:
  - job: Deploy
    steps:
    - script: echo running UnitTest
