trigger:
- none

pool: 30530-ICAP-SDP-DevOps-AgentPool

steps: 
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 30530-ICAP-SDP-NPRD-ServiceConnection
    scriptType: ps core
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
