# azure-pipelines.yml
resources:
  repositories:
  - repository: templates
    type: github
    name: jingxuezhou/templates
    endpoint: jingxuezhou

trigger:
- none

pool: 30530-ICAP-SDP-DevOps-AgentPool

extends:
  template: template.yml@templates
  parameters:
    usersteps:
    - script: echo This is my first step
    - script: echo This is my second step
jobs:
- job: buildNormal
  steps:
  - script: echo Building the normal, unsensitive part
- ${{ if eq(variables['Build.SourceBranchName'], 'refs/heads/main') }}:
  - job: buildMainOnly
    steps:
    - script: echo Building the restricted part that only builds for main branch
