trigger:
- none

pool: 30530-ICAP-SDP-DevOps-AgentPool

steps: 
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: 3377047f-02a8-4316-91eb-99afd67a0352
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show
